#!/bin/sh
APPDIR=`dirname $0`;
$JAVA/bin/java -cp "$PROJECTPATH" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src org.openelis.portal.messages.PortalMessages -createMessages -extends org.openelis.ui.messages.UIMessages;

