-------------------------------------------------------------------------------
--
-- permission
--
-------------------------------------------------------------------------------

grant select,insert,update,delete on address to "jboss_dev";
grant select,insert,update,delete on analysis to "jboss_dev";
grant select,insert,update,delete on analysis_qaevent to "jboss_dev";
grant select,insert,update,delete on analysis_report_flags to "jboss_dev";
grant select,insert,update,delete on analysis_user to "jboss_dev";
grant select,insert,update,delete on analyte to "jboss_dev";
grant select,insert,update,delete on analyte_parameter to "jboss_dev";
grant select,insert,update,delete on attachment to "jboss_dev";
grant select,insert,update,delete on attachment_issue to "jboss_dev";
grant select,insert,update,delete on attachment_item to "jboss_dev";
grant select,insert,update,delete on aux_data to "jboss_dev";
grant select,insert,update,delete on aux_field to "jboss_dev";
grant select,insert,update,delete on aux_field_group to "jboss_dev";
grant select,insert,update,delete on aux_field_value to "jboss_dev";
grant select,insert,update,delete on category to "jboss_dev";
grant select,insert,update,delete on cron to "jboss_dev";
grant select,insert,update,delete on dictionary to "jboss_dev";
grant select,insert,update,delete on eorder to "jboss_dev";
grant select,insert,update,delete on eorder_body to "jboss_dev";
grant select,insert,update,delete on eorder_link to "jboss_dev";
grant select,insert,update,delete on event_log to "jboss_dev";
grant select,insert,update,delete on exchange_criteria to "jboss_dev";
grant select,insert,update,delete on exchange_external_term to "jboss_dev";
grant select,insert,update,delete on exchange_local_term to "jboss_dev";
grant select,insert,update,delete on exchange_profile to "jboss_dev";
grant select,insert,update,delete on history to "jboss_dev";
grant select,insert,update,delete on instrument to "jboss_dev";
grant select,insert,update,delete on instrument_log to "jboss_dev";
grant select,insert,update,delete on inventory_adjustment to "jboss_dev";
grant select,insert,update,delete on inventory_component to "jboss_dev";
grant select,insert,update,delete on inventory_item to "jboss_dev";
grant select,insert,update,delete on inventory_location to "jboss_dev";
grant select,insert,update,delete on inventory_receipt to "jboss_dev";
grant select,insert,update,delete on inventory_receipt_iorder_item to "jboss_dev";
grant select,insert,update,delete on inventory_x_adjust to "jboss_dev";
grant select,insert,update,delete on inventory_x_put to "jboss_dev";
grant select,insert,update,delete on inventory_x_use to "jboss_dev";
grant select,insert,update,delete on label to "jboss_dev";
grant select,insert,update,delete on lock to "jboss_dev";
grant select,insert,update,delete on method to "jboss_dev";
grant select,insert,update,delete on note to "jboss_dev";
grant select,insert,update,delete on iorder to "jboss_dev";
grant select,insert,update,delete on iorder_container to "jboss_dev";
grant select,insert,update,delete on iorder_item to "jboss_dev";
grant select,insert,update,delete on iorder_organization to "jboss_dev";
grant select,insert,update,delete on iorder_recurrence to "jboss_dev";
grant select,insert,update,delete on iorder_test_analyte to "jboss_dev";
grant select,insert,update,delete on iorder_test to "jboss_dev";
grant select,insert,update,delete on organization to "jboss_dev";
grant select,insert,update,delete on organization_contact to "jboss_dev";
grant select,insert,update,delete on organization_parameter to "jboss_dev";
grant select,insert,update,delete on panel to "jboss_dev";
grant select,insert,update,delete on panel_item to "jboss_dev";
grant select,insert,update,delete on patient to "jboss_dev";
grant select,insert,update,delete on patient_relation to "jboss_dev";
grant select,insert,update,delete on preferences to "jboss_dev";
grant select,insert,update,delete on project to "jboss_dev";
grant select,insert,update,delete on project_parameter to "jboss_dev";
grant select,insert,update,delete on provider to "jboss_dev";
grant select,insert,update,delete on provider_location to "jboss_dev";
grant select,insert,update,delete on pws to "jboss_dev";
grant select,insert,update,delete on pws_address to "jboss_dev";
grant select,insert,update,delete on pws_facility to "jboss_dev";
grant select,insert,update,delete on pws_monitor to "jboss_dev";
grant select,insert,update,delete on pws_violation to "jboss_dev";
grant select,insert,update,delete on qaevent to "jboss_dev";
grant select,insert,update,delete on qc to "jboss_dev";
grant select,insert,update,delete on qc_analyte to "jboss_dev";
grant select,insert,update,delete on qc_lot to "jboss_dev";
grant select,insert,update,delete on result to "jboss_dev";
grant select,insert,update,delete on sample to "jboss_dev";
grant select,insert,update,delete on sample_animal to "jboss_dev";
grant select,insert,update,delete on sample_clinical to "jboss_dev";
grant select,insert,update,delete on sample_environmental to "jboss_dev";
grant select,insert,update,delete on sample_item to "jboss_dev";
grant select,insert,update,delete on sample_neonatal to "jboss_dev";
grant select,insert,update,delete on sample_organization to "jboss_dev";
grant select,insert,update,delete on sample_private_well to "jboss_dev";
grant select,insert,update,delete on sample_project to "jboss_dev";
grant select,insert,update,delete on sample_pt to "jboss_dev";
grant select,insert,update,delete on sample_qaevent to "jboss_dev";
grant select,insert,update,delete on sample_sdwis to "jboss_dev";
grant select,insert,update,delete on scriptlet to "jboss_dev";
grant select,insert,update,delete on section to "jboss_dev";
grant select,insert,update,delete on section_parameter to "jboss_dev";
grant select,insert,update,delete on shipping to "jboss_dev";
grant select,insert,update,delete on shipping_item to "jboss_dev";
grant select,insert,update,delete on shipping_tracking to "jboss_dev";
grant select,insert,update,delete on standard_note to "jboss_dev";
grant select,insert,update,delete on storage to "jboss_dev";
grant select,insert,update,delete on storage_location to "jboss_dev";
grant select,insert,update,delete on storage_unit to "jboss_dev";
grant select,insert,update,delete on system_variable to "jboss_dev";
grant select,insert,update,delete on test to "jboss_dev";
grant select,insert,update,delete on test_analyte to "jboss_dev";
grant select,insert,update,delete on test_prep to "jboss_dev";
grant select,insert,update,delete on test_reflex to "jboss_dev";
grant select,insert,update,delete on test_result to "jboss_dev";
grant select,insert,update,delete on test_section to "jboss_dev";
grant select,insert,update,delete on test_trailer to "jboss_dev";
grant select,insert,update,delete on test_type_of_sample to "jboss_dev";
grant select,insert,update,delete on test_worksheet to "jboss_dev";
grant select,insert,update,delete on test_worksheet_analyte to "jboss_dev";
grant select,insert,update,delete on test_worksheet_item to "jboss_dev";
grant select,insert,update,delete on worksheet to "jboss_dev";
grant select,insert,update,delete on worksheet_analysis to "jboss_dev";
grant select,insert,update,delete on worksheet_item to "jboss_dev";
grant select,insert,update,delete on worksheet_qc_result to "jboss_dev";
grant select,insert,update,delete on worksheet_reagent to "jboss_dev";
grant select,insert,update,delete on worksheet_result to "jboss_dev";

grant select on analysis_view to "jboss_dev";
grant select on sample_patient_view to "jboss_dev";
grant select on sample_view to "jboss_dev";
grant select on test_analyte_view to "jboss_dev";
grant select on todo_sample_view to "jboss_dev";
grant select on worksheet_analysis_view to "jboss_dev";
grant select on worksheet_qc_result_view to "jboss_dev";

grant usage,select on sequence address_id_seq to "jboss_dev";
grant usage,select on sequence analysis_id_seq to "jboss_dev";
grant usage,select on sequence analysis_qaevent_id_seq to "jboss_dev";
grant usage,select on sequence analysis_user_id_seq to "jboss_dev";
grant usage,select on sequence analyte_id_seq to "jboss_dev";
grant usage,select on sequence analyte_parameter_id_seq to "jboss_dev";
grant usage,select on sequence attachment_id_seq to "jboss_dev";
grant usage,select on sequence attachment_issue_id_seq to "jboss_dev";
grant usage,select on sequence attachment_item_id_seq to "jboss_dev";
grant usage,select on sequence aux_data_id_seq to "jboss_dev";
grant usage,select on sequence aux_field_group_id_seq to "jboss_dev";
grant usage,select on sequence aux_field_id_seq to "jboss_dev";
grant usage,select on sequence aux_field_value_id_seq to "jboss_dev";
grant usage,select on sequence category_id_seq to "jboss_dev";
grant usage,select on sequence cron_id_seq to "jboss_dev";
grant usage,select on sequence dictionary_id_seq to "jboss_dev";
grant usage,select on sequence eorder_id_seq to "jboss_dev";
grant usage,select on sequence eorder_body_id_seq to "jboss_dev";
grant usage,select on sequence eorder_link_id_seq to "jboss_dev";
grant usage,select on sequence event_log_id_seq to "jboss_dev";
grant usage,select on sequence exchange_criteria_id_seq to "jboss_dev";
grant usage,select on sequence exchange_external_term_id_seq to "jboss_dev";
grant usage,select on sequence exchange_local_term_id_seq to "jboss_dev";
grant usage,select on sequence exchange_profile_id_seq to "jboss_dev";
grant usage,select on sequence history_id_seq to "jboss_dev";
grant usage,select on sequence instrument_id_seq to "jboss_dev";
grant usage,select on sequence instrument_log_id_seq to "jboss_dev";
grant usage,select on sequence inventory_adjustment_id_seq to "jboss_dev";
grant usage,select on sequence inventory_component_id_seq to "jboss_dev";
grant usage,select on sequence inventory_item_id_seq to "jboss_dev";
grant usage,select on sequence inventory_location_id_seq to "jboss_dev";
grant usage,select on sequence inventory_receipt_id_seq to "jboss_dev";
grant usage,select on sequence inventory_receipt_iorder_item_id_seq to "jboss_dev";
grant usage,select on sequence inventory_x_adjust_id_seq to "jboss_dev";
grant usage,select on sequence inventory_x_put_id_seq to "jboss_dev";
grant usage,select on sequence inventory_x_use_id_seq to "jboss_dev";
grant usage,select on sequence iorder_id_seq to "jboss_dev";
grant usage,select on sequence iorder_container_id_seq to "jboss_dev";
grant usage,select on sequence iorder_item_id_seq to "jboss_dev";
grant usage,select on sequence iorder_organization_id_seq to "jboss_dev";
grant usage,select on sequence iorder_recurrence_id_seq to "jboss_dev";
grant usage,select on sequence iorder_test_id_seq to "jboss_dev";
grant usage,select on sequence iorder_test_analyte_id_seq to "jboss_dev";
grant usage,select on sequence label_id_seq to "jboss_dev";
grant usage,select on sequence method_id_seq to "jboss_dev";
grant usage,select on sequence note_id_seq to "jboss_dev";
grant usage,select on sequence organization_id_seq to "jboss_dev";
grant usage,select on sequence organization_contact_id_seq to "jboss_dev";
grant usage,select on sequence organization_parameter_id_seq to "jboss_dev";
grant usage,select on sequence panel_id_seq to "jboss_dev";
grant usage,select on sequence panel_item_id_seq to "jboss_dev";
grant usage,select on sequence patient_id_seq to "jboss_dev";
grant usage,select on sequence patient_relation_id_seq to "jboss_dev";
grant usage,select on sequence project_id_seq to "jboss_dev";
grant usage,select on sequence project_parameter_id_seq to "jboss_dev";
grant usage,select on sequence provider_id_seq to "jboss_dev";
grant usage,select on sequence provider_location_id_seq to "jboss_dev";
grant usage,select on sequence pws_id_seq to "jboss_dev";
grant usage,select on sequence pws_violation_id_seq to "jboss_dev";
grant usage,select on sequence qaevent_id_seq to "jboss_dev";
grant usage,select on sequence qc_id_seq to "jboss_dev";
grant usage,select on sequence qc_analyte_id_seq to "jboss_dev";
grant usage,select on sequence qc_lot_id_seq to "jboss_dev";
grant usage,select on sequence result_id_seq to "jboss_dev";
grant usage,select on sequence sample_id_seq to "jboss_dev";
grant usage,select on sequence sample_animal_id_seq to "jboss_dev";
grant usage,select on sequence sample_clinical_id_seq to "jboss_dev";
grant usage,select on sequence sample_environmental_id_seq to "jboss_dev";
grant usage,select on sequence sample_item_id_seq to "jboss_dev";
grant usage,select on sequence sample_neonatal_id_seq to "jboss_dev";
grant usage,select on sequence sample_organization_id_seq to "jboss_dev";
grant usage,select on sequence sample_private_well_id_seq to "jboss_dev";
grant usage,select on sequence sample_project_id_seq to "jboss_dev";
grant usage,select on sequence sample_pt_id_seq to "jboss_dev";
grant usage,select on sequence sample_qaevent_id_seq to "jboss_dev";
grant usage,select on sequence sample_sdwis_id_seq to "jboss_dev";
grant usage,select on sequence scriptlet_id_seq to "jboss_dev";
grant usage,select on sequence section_id_seq to "jboss_dev";
grant usage,select on sequence section_parameter_id_seq to "jboss_dev";
grant usage,select on sequence shipping_id_seq to "jboss_dev";
grant usage,select on sequence shipping_item_id_seq to "jboss_dev";
grant usage,select on sequence shipping_tracking_id_seq to "jboss_dev";
grant usage,select on sequence standard_note_id_seq to "jboss_dev";
grant usage,select on sequence storage_id_seq to "jboss_dev";
grant usage,select on sequence storage_location_id_seq to "jboss_dev";
grant usage,select on sequence storage_unit_id_seq to "jboss_dev";
grant usage,select on sequence system_variable_id_seq to "jboss_dev";
grant usage,select on sequence test_id_seq to "jboss_dev";
grant usage,select on sequence test_analyte_id_seq to "jboss_dev";
grant usage,select on sequence test_prep_id_seq to "jboss_dev";
grant usage,select on sequence test_reflex_id_seq to "jboss_dev";
grant usage,select on sequence test_result_id_seq to "jboss_dev";
grant usage,select on sequence test_section_id_seq to "jboss_dev";
grant usage,select on sequence test_trailer_id_seq to "jboss_dev";
grant usage,select on sequence test_type_of_sample_id_seq to "jboss_dev";
grant usage,select on sequence test_worksheet_id_seq to "jboss_dev";
grant usage,select on sequence test_worksheet_analyte_id_seq to "jboss_dev";
grant usage,select on sequence test_worksheet_item_id_seq to "jboss_dev";
grant usage,select on sequence worksheet_id_seq to "jboss_dev";
grant usage,select on sequence worksheet_analysis_id_seq to "jboss_dev";
grant usage,select on sequence worksheet_item_id_seq to "jboss_dev";
grant usage,select on sequence worksheet_qc_result_id_seq to "jboss_dev";
grant usage,select on sequence worksheet_reagent_id_seq to "jboss_dev";
grant usage,select on sequence worksheet_result_id_seq to "jboss_dev";
