#!/bin/sh
APPDIR=`dirname $0`;
TOOLS='/home/tschmidt/workspace/UHL-GWT-tools/gwt-linux-UHL.1.4';
java -Xmx512m -cp "$APPDIR/src:$APPDIR/bin:$TOOLS/gwt-user.jar:$TOOLS/gwt-dev-linux.jar:../OpenELIS-Lib/openelis-lib.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" org.openelis.OpenELIS;
